### ISSUE TITLE
Arch Linux Crash on Startup

### ISSUE THREAD

**Issue by fundies** [IsmAvatar/LateralGM#141]
Operating System: Linux
Version: 3.15.7-1-ARCH
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_65

Available processors (cores): 8
Free memory (bytes): 193632344
Maximum memory (bytes): 3719299072
Total memory available to JVM (bytes): 276824064

File system root: /
Total space (bytes): 738261639168
Free space (bytes): 292187881472
Usable space (bytes): 288420265984

Stack trace:
java.lang.ArrayIndexOutOfBoundsException: 9 >= 8
	at java.util.Vector.elementAt(Vector.java:470)
	at com.sun.java.swing.plaf.gtk.GTKFileChooserUI$GTKFileListModel.getElementAt(GTKFileChooserUI.java:987)
	at javax.swing.JList.getSelectedValue(JList.java:2343)
	at com.sun.java.swing.plaf.gtk.GTKFileChooserUI$SelectionListener.valueChanged(GTKFileChooserUI.java:456)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1798)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1812)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:632)
	at javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2580)
	at javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:148)
	at com.sun.java.swing.plaf.gtk.GTKFileChooserUI$GTKFileListModel.intervalAdded(GTKFileChooserUI.java:991)
	at javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:148)
	at javax.swing.plaf.basic.BasicDirectoryModel.access$700(BasicDirectoryModel.java:43)
	at javax.swing.plaf.basic.BasicDirectoryModel$DoChangeContents.run(BasicDirectoryModel.java:490)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:741)
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:639)
	at org.lateralgm.main.FileChooser.openNewFile(FileChooser.java:511)
	at org.lateralgm.main.FileChooser.open(FileChooser.java:522)
	at org.lateralgm.main.Listener.actionPerformed(Listener.java:293)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by RobertBColton** [comment]
Ok, I am certain this issue was with OpenJDK. LGM has these problems of calling UI code when not on the EDT which we cover in #227. What happened was that LGM thought you passed a file on the CMD line and then it didn't exist so it went to show you a file open dialog off the EDT which led to the exceptions.

I am closing this issue because #227 basically includes it, LGM needs a huge revamp to stop calling UI code on the EDT.
