### ISSUE TITLE
Reading of egm files is broken

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#213]
Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_25

Available processors (cores): 8
Free memory (bytes): 225449064
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259588096

File system root: C:\
Total space (bytes): 999964012544
Free space (bytes): 790014722048
Usable space (bytes): 790014722048

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.NullPointerException
	at org.enigma.file.EFileReader.readResource(EFileReader.java:666)
	at org.enigma.file.EFileReader.processEntries(EFileReader.java:644)
	at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:622)
	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:560)
	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:538)
	at org.enigma.file.EgmIO.read(EgmIO.java:56)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:564)
	at java.lang.Thread.run(Unknown Source)

**Comment by RobertBColton** [comment]
@egofree71 I updated sorloks ticket with this already on the plugin tracker https://github.com/enigma-dev/lgmplugin/issues/29
