### ISSUE TITLE
Unhandled Exception on OS X

### ISSUE THREAD

**Issue by daxxog** [IsmAvatar/LateralGM#217]
```

Operating System: Mac OS X
Version: 10.10.2
Architecture: x86_64

Java Vendor: Oracle Corporation
Version: 1.8.0_40

Available processors (cores): 4
Free memory (bytes): 103066136
Maximum memory (bytes): 1908932608
Total memory available to JVM (bytes): 128974848

File system root: /
Total space (bytes): 498876809216
Free space (bytes): 11955982336
Usable space (bytes): 11693838336

Stack trace:
java.net.URISyntaxException: Illegal character in path at index 31: /Users/daxxog/Desktop/Halo-test game.gm6
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:143)
	at org.lateralgm.main.LGM.main(LGM.java:2382)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(SplashScreen.java:197)
	at java.awt.SplashScreen.update(SplashScreen.java:324)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:2892)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:2885)
	at org.lateralgm.main.LGM.main(LGM.java:2388)

```

**Comment by daxxog** [comment]
Did some digging. Fixed it using this quick hack.

```java
/* CleanLGM.java
 * Cleans LateralGM Preferences
 * (c) 2015 David (daXXog) Volm ><> + + + <><
 * Released under Apache License, Version 2.0:
 * http://www.apache.org/licenses/LICENSE-2.0.html  
 */ 

import java.util.prefs.Preferences;

public class CleanLGM {
	public static void main(String[] args) {
		Preferences PREFS = Preferences.userRoot().node("/org/lateralgm");
		PREFS.remove("FILE_RECENT");
		System.out.println("Cleaned LateralGM Preferences.");
	}
}
```
