### ISSUE TITLE
Swing Sort Policy Errors

### ISSUE THREAD

**Issue by paulkokos** [IsmAvatar/LateralGM#218]
Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_45

Available processors (cores): 4
Free memory (bytes): 224754696
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: A:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: C:\
Total space (bytes): 161679929344
Free space (bytes): 29977178112
Usable space (bytes): 29977178112

File system root: D:\
Total space (bytes): 536979144704
Free space (bytes): 187956035584
Usable space (bytes): 187956035584

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: G:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: L:\
Total space (bytes): 678842368
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.ClassCastException
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.enumerateAndSortCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFocusTraversalCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.LayoutFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getDefaultComponent(Unknown Source)
	at java.awt.FocusTraversalPolicy.getInitialComponent(Unknown Source)
	at java.awt.Window.getMostRecentFocusOwner(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.SequencedEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by RobertBColton** [comment]
@paulkokos Thank you for reporting this issue. This looks like a bug that I was previously trying to reproduce and I feel may be a bug in OpenJDK iirc.

May I ask what you were doing when the exception occurred?

**Comment by RobertBColton** [comment]
This seems to have been caused by us creating the main frame in the initial thread which is not the EDT and #506 should have resolved now. Feel free to try the latest releases!
https://stackoverflow.com/a/36746818
