### ISSUE TITLE
Not compatible with Win10 x64/Java 8 U60 x64

### ISSUE THREAD

**Issue by Something54363** [IsmAvatar/LateralGM#226]
I could not get LateralGM to initialize, here is the error log:
```
Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_60

Available processors (cores): 2
Free memory (bytes): 220313784
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 272884559872
Free space (bytes): 121228492800
Usable space (bytes): 121228492800

File system root: D:\
Total space (bytes): 31133265920
Free space (bytes): 29879394304
Usable space (bytes): 29879394304

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.ClassCastException
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.enumerateAndSortCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFocusTraversalCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.LayoutFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getDefaultComponent(Unknown Source)
	at java.awt.FocusTraversalPolicy.getInitialComponent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.SequencedEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
I used the portable Windows installer.

**Comment by RobertBColton** [comment]
@Something54363 This is actually a _ problem that is well detailed on the Wiki.
You can use LateralGM with a 64 bit Java installation if you do not use ENIGMA. ENIGMA does not support 64 bit game compilation or LGM on Windows.
http://enigma-dev.org/docs/Wiki/Troubleshoot
If you wish to use ENIGMA and LateralGM together you will need to install 32 bit Java in parallel or uninstall and replace your 64 bit version with the 32 bit version.
http://enigma-dev.org/docs/Wiki/Install:Parallel_Java
