### ISSUE TITLE
java.lang.NoSuchFieldError: lnfFont [1.8.7]

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#276]
```
Operating System: Linux
Version: 3.19.0-58-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_95

Available processors (cores): 4
Free memory (bytes): 41215400
Maximum memory (bytes): 620756992
Total memory available to JVM (bytes): 68681728

File system root: /
Total space (bytes): 28875468800
Free space (bytes): 12173590528
Usable space (bytes): 10683166720

Stack trace:

java.lang.NoSuchFieldError: lnfFont
	at org.enigma.EnigmaRunner.populateMenu(EnigmaRunner.java:424)
	at org.enigma.EnigmaRunner.<init>(EnigmaRunner.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:752)
	at org.lateralgm.main.LGM.main(LGM.java:2464)

```

**Comment by RobertBColton** [comment]
Sigh, this I was not expecting. The reason this broke is because I was hard coding a look and feel, called the Quantum look and feel, inside LateralGM. I decided to remove this in the latest release because LGM has plugins and supports Java's pluggable look and feel system, so there is no need to embed look and feels directly inside LGM. It looks like I'll have to go and update the plugin too. I guess that's find because I have to fix an issue with ENIGMA.exe anyway I think.
https://github.com/enigma-dev/lgmplugin/blob/302fc443e7e2b28df8126225fb74b2ee4e3d20e5/org/enigma/EnigmaRunner.java#L423

**Comment by RobertBColton** [comment]
This [has been fixed in the plugin](https://github.com/enigma-dev/lgmplugin/commit/64518b52819ad8f65d6739da867ef51b9088f9ac), please download the new plugin from Extra Packages.
http://enigma-dev.org/docs/Wiki/Install:Extra_Packages#The_Plugin

**Comment by faissaloo** [comment]
Yup, works fine now, thanks.

**Comment by RobertBColton** [comment]
No problem! :smile_cat:
