### ISSUE TITLE
Two Unhandled Exceptions at ENIGMA starup

### ISSUE THREAD

**Issue by Atulin** [IsmAvatar/LateralGM#283]
The first one:

```

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_91

Available processors (cores): 4
Free memory (bytes): 220157456
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 118106353664
Free space (bytes): 14949666816
Usable space (bytes): 14949666816

File system root: D:\
Total space (bytes): 881988317184
Free space (bytes): 119582765056
Usable space (bytes): 119582765056

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 1000202039296
Free space (bytes): 709530775552
Usable space (bytes): 709530775552

File system root: G:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: J:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: Q:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.ClassCastException
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at javax.swing.LayoutComparator.compare(Unknown Source)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.enumerateAndSortCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFocusTraversalCycle(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.LayoutFocusTraversalPolicy.getFirstComponent(Unknown Source)
	at javax.swing.SortingFocusTraversalPolicy.getDefaultComponent(Unknown Source)
	at java.awt.FocusTraversalPolicy.getInitialComponent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.SequencedEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

The second one:

```
Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_91

Available processors (cores): 4
Free memory (bytes): 205006072
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 118106353664
Free space (bytes): 14952669184
Usable space (bytes): 14952669184

File system root: D:\
Total space (bytes): 881988317184
Free space (bytes): 119582765056
Usable space (bytes): 119582765056

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 1000202039296
Free space (bytes): 709561675776
Usable space (bytes): 709561675776

File system root: G:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: J:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: Q:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/F:/Engines/ENIGMA/ENIGMA/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

```

**Comment by RobertBColton** [comment]
Please see the running parallel Java article on the Wiki. ENIGMA needs a 32 bit Java installation.
http://enigma-dev.org/docs/Wiki/Install:Parallel_Java

**Comment by RobertBColton** [comment]
Closing this issue unless additional information is requested.
