### ISSUE TITLE
Error reading sounds

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#298]
The file I was trying to load: https://github.com/faissaloo/xor/tree/master/xor.gmx  
This was loading fine in the last LGM that was bundled with ENIGMA.
```
Operating System: Linux
Version: 3.19.0-59-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_101

Available processors (cores): 4
Free memory (bytes): 173007808
Maximum memory (bytes): 620756992
Total memory available to JVM (bytes): 329252864

File system root: /
Total space (bytes): 28875468800
Free space (bytes): 7192608768
Usable space (bytes): 5702184960

Stack trace:
org.lateralgm.file.GmFormatException: java.lang.ArrayIndexOutOfBoundsException: 16
	at org.lateralgm.file.GMXFileReader.iterateSounds(GMXFileReader.java:675)
	at org.lateralgm.file.GMXFileReader.readSounds(GMXFileReader.java:721)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:246)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:201)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:587)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by RobertBColton** [comment]
There was a bug in the last LGM's version sound editor that wrote type and kind wrong.

The problem in each of your sound files is this:
```xml
  <types>
    <type>16</type>
  </types>
```

Just change the 16 to 0 in all your project.gmx/sound/*.sound.gmx files. Then try loading the project in LGM again and let me know if that works.
