### ISSUE TITLE
LateralGM error report

### ISSUE THREAD

**Issue by Mikelle02** [IsmAvatar/LateralGM#308]
Operating System: Linux
Version: 4.4.0-34-generic
Architecture: i386

Java Name: Java HotSpot(TM) Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_101

Available processors (cores): 2
Free memory (bytes): 21043176
Maximum memory (bytes): 462422016
Total memory available to JVM (bytes): 32243712

File system root: /
Total space (bytes): 243863789568
Free space (bytes): 228002320384
Usable space (bytes): 215591165952

Stack trace:
java.util.ConcurrentModificationException
	at java.util.SubList.checkForComodification(AbstractList.java:769)
	at java.util.SubList.listIterator(AbstractList.java:695)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.Collections$SynchronizedList.listIterator(Collections.java:2441)
	at java.util.AbstractList.equals(AbstractList.java:519)
	at java.util.Collections$SynchronizedList.equals(Collections.java:2410)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread$1.call(BasicDirectoryModel.java:297)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread$1.call(BasicDirectoryModel.java:275)
	at sun.awt.shell.ShellFolderManager$DirectInvoker.invoke(ShellFolderManager.java:113)
	at sun.awt.shell.ShellFolder.invoke(ShellFolder.java:518)
	at sun.awt.shell.ShellFolder.invoke(ShellFolder.java:504)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run0(BasicDirectoryModel.java:275)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(BasicDirectoryModel.java:228)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(SplashScreen.java:197)
	at java.awt.SplashScreen.update(SplashScreen.java:324)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:2796)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:2789)
	at org.lateralgm.main.LGM.main(LGM.java:2274)

**Comment by RobertBColton** [comment]
@Mikelle02 does this occur every time you run LGM?
