### ISSUE TITLE
Can't edit sub-images on the sprite screen

### ISSUE THREAD

**Issue by Shakaka88** [IsmAvatar/LateralGM#309]
Pasted below the error that comes up when I try to edit sub-images on the sprite creation screen
Operating System: Linux
Version: 4.4.0-36-generic
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_101

Available processors (cores): 2
Free memory (bytes): 53416088
Maximum memory (bytes): 863502336
Total memory available to JVM (bytes): 114819072

File system root: /
Total space (bytes): 310427131904
Free space (bytes): 300072738816
Usable space (bytes): 284280348672

Stack trace:
java.lang.UnsupportedOperationException: no internal or system sprite editor
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.start(SpriteFrame.java:1794)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.<init>(SpriteFrame.java:1770)
	at org.lateralgm.subframes.SpriteFrame.editSubimage(SpriteFrame.java:1718)
	at org.lateralgm.subframes.SpriteFrame.editActionsPerformed(SpriteFrame.java:1302)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1386)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException: The EDIT action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.edit(Desktop.java:300)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.start(SpriteFrame.java:1790)
	... 41 more

**Comment by faissaloo** [comment]
Go to:  
file -> Preferences -> External Editors  
and set a background and sprite editor, for example GIMP (which is what I use) would be: 
```
gimp %s
```

**Comment by Shakaka88** [comment]
You're my hero! I figured that's what I had to do but wasn't sure how! Thank you so much!

**Comment by RobertBColton** [comment]
Thank goodness that still works :smile: we're here if you have any other issues.

**Comment by faissaloo** [comment]
@RobertBColton Thanks man :)

**Comment by RobertBColton** [comment]
After some more research this was actually saying his Java installation couldn't find a suitable program to open for the file type, which is PNG by default in LGM. I guess it can be fixed by installing some GNOME libraries, it's a pretty common issue on Linux. I am going to add this one to the Wiki I think.

http://stackoverflow.com/questions/10051082/ubuntu-11-10-java-awt-desktop-not-supported
http://stackoverflow.com/questions/102325/not-supported-platforms-for-java-awt-desktop-getdesktop
