### ISSUE TITLE
"Unable to Update Enigma" error on launch with symlink

### ISSUE THREAD

**Issue by templink** [IsmAvatar/LateralGM#310]
Operating System: Linux
Version: 4.4.0-36-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_91

Available processors (cores): 4
Free memory (bytes): 149452056
Maximum memory (bytes): 3728736256
Total memory available to JVM (bytes): 202899456

File system root: /
Total space (bytes): 245997502464
Free space (bytes): 203712487424
Usable space (bytes): 191192858624

Stack trace:
org.lateralgm.file.GmFormatException: java.io.FileNotFoundException: Compilers/Linux/gcc.ey (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.util.Scanner.<init>(Scanner.java:635)
	at java.util.Scanner.<init>(Scanner.java:629)
	at org.enigma.file.YamlParser.parse(YamlParser.java:189)
	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:278)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:174)

**Comment by faissaloo** [comment]
Make sure to change your working directory with `cd` to the top level enigma-dev directory before you start ENIGMA.

**Comment by RobertBColton** [comment]
These issues actually belong on the plugin tracker. Also, we do not recommend the OpenJDK. Can you please try Oracle JDK?
