### ISSUE TITLE
Unhandled Exception when creating a sprite

### ISSUE THREAD

**Issue by bonezinger** [IsmAvatar/LateralGM#328]
The errors aren't critical, things still work as expected, despite them showing up.

Step by step of what I did:

1. Create a new Sprite
2. Add Spritesheet Subimage
3. Choose the image (https://imgur.com/kBZ2aVt)
4. On the next screen to define the sizes:
5. --Number of Images = 8
6. --Images per row = 2
7. --Image (cell) width=  128
8. --Image (cell) height = 128
9. Click Import

So far, so good. However, as soon as I click the arrow to change the frame, or click any of the frames, the following error occurs. 
```
Operating System: Windows 10
Version: 10.0
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_144

Available processors (cores): 4
Free memory (bytes): 97755888
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 368574464

File system root: C:\
Total space (bytes): 195964182528
Free space (bytes): 68331991040
Usable space (bytes): 68331991040

File system root: D:\
Total space (bytes): 280513998848
Free space (bytes): 84925399040
Usable space (bytes): 84925399040

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.IllegalArgumentException: Raster ByteInterleavedRaster: width = 256 height = 512 #numDataElements 3 dataOff[0] = 2 has minX or minY not equal to zero: -128 0
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at org.lateralgm.components.ImageEffects$BlackAndWhiteEffect.getAppliedImage(ImageEffects.java:100)
	at org.lateralgm.components.EffectsFrame.updatePreviews(EffectsFrame.java:304)
	at org.lateralgm.components.EffectsFrame.setImages(EffectsFrame.java:270)
	at org.lateralgm.components.EffectsFrame.getInstance(EffectsFrame.java:86)
	at org.lateralgm.subframes.SpriteFrame$5.valueChanged(SpriteFrame.java:904)
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JList.setSelectionInterval(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI$Handler.adjustSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

If I click to Save, it gives me another error message only once. If I click the save button again, it doesn't show the message. Here's the error:
```
Stack trace:
java.lang.IllegalArgumentException: Width or height of BufferedImages do not match
	at java.awt.image.ColorConvertOp.ICCBIFilter(Unknown Source)
	at java.awt.image.ColorConvertOp.filter(Unknown Source)
	at org.lateralgm.components.ImageEffects$BlackAndWhiteEffect.getAppliedImage(ImageEffects.java:103)
	at org.lateralgm.components.EffectsFrame.updatePreviews(EffectsFrame.java:304)
	at org.lateralgm.components.EffectsFrame.setImages(EffectsFrame.java:270)
	at org.lateralgm.components.EffectsFrame.getInstance(EffectsFrame.java:86)
	at org.lateralgm.subframes.SpriteFrame$5.valueChanged(SpriteFrame.java:904)
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(Unknown Source)
	at javax.swing.DefaultListSelectionModel.clearSelection(Unknown Source)
	at javax.swing.JList.clearSelection(Unknown Source)
	at javax.swing.JList.setModel(Unknown Source)
	at javax.swing.JList.setListData(Unknown Source)
	at org.lateralgm.subframes.SpriteFrame.updateImageList(SpriteFrame.java:1672)
	at org.lateralgm.subframes.SpriteFrame.updated(SpriteFrame.java:1742)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:137)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:1)
	at org.lateralgm.util.SetTraverser.traverse(SetTraverser.java:72)
	at org.lateralgm.main.UpdateSource.fireUpdate(UpdateSource.java:63)
	at org.lateralgm.main.UpdateSource.access$0(UpdateSource.java:61)
	at org.lateralgm.main.UpdateSource$UpdateTrigger.fire(UpdateSource.java:98)
	at org.lateralgm.resources.Resource.fireUpdate(Resource.java:111)
	at org.lateralgm.resources.Sprite.fireUpdate(Sprite.java:285)
	at org.lateralgm.resources.Resource.setName(Resource.java:122)
	at org.lateralgm.subframes.SpriteFrame.commitChanges(SpriteFrame.java:1095)
	at org.lateralgm.subframes.ResourceFrame.resourceChanged(ResourceFrame.java:182)
	at org.lateralgm.subframes.ResourceFrame.doDefaultSaveAction(ResourceFrame.java:234)
	at org.lateralgm.subframes.ResourceFrame.actionPerformed(ResourceFrame.java:245)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1559)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by RobertBColton** [comment]
Closing as resolved, I've patched this in the 1.8.33 release:
https://github.com/IsmAvatar/LateralGM/releases/tag/v1.8.33
