### ISSUE TITLE
LateralGM version 1.8.1 fail to load working projects

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#336]
I tried to use the newest version of LateralGM but JAVA crashes or various errors either get reported

LateralGM Version: 1.8.10

Operating System: Linux
Version: 3.16.0-4-686-pae
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_151

Available processors (cores): 2
Free memory (bytes): 80408760
Maximum memory (bytes): 818413568
Total memory available to JVM (bytes): 106430464

File system root: /
Total space (bytes): 155247083520
Free space (bytes): 137005674496
Usable space (bytes): 129095901184

Stack trace:
org.lateralgm.file.GmFormatException: failed to read: /home/hughie/enigma_Projects/dialog_sample.gmx/Configs\Default\windows\runner_icon.ico
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:470)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:295)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:233)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/hughie/enigma_Projects/dialog_sample.gmx/Configs\Default\windows\runner_icon.ico (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.lateralgm.file.StreamDecoder.<init>(StreamDecoder.java:45)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:75)
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:466)
	... 5 more

This happened from running the same file with version 1.8.7
![screenshot](https://user-images.githubusercontent.com/19632613/34654855-ab54de94-f3d7-11e7-9b94-15ab286d3996.png)

**Comment by RobertBColton** [comment]
This one is simple, good thing you upgraded. Basically, your game is missing its icon, just create the following file:
"/home/hughie/enigma_Projects/dialog_sample.gmx/Configs\Default\windows\runner_icon.ico"
With the newer version you should be able to just do it through the game settings UI without any problem and then save the GMX. This error should be harmless. If neither of those works, please let me know.

**Comment by Hughtech** [comment]
the error continued to show with **all** of my sample projects. I had deleted it and copied back over version 1.8.7 and everything's fine. i have been busy writing up some tutorials so i wasn't able to follow up. I am in the process of creating a new test project, will save it, then reload it again to see what happens.

**Comment by RobertBColton** [comment]
Ok, but actually this can be kind of considered a fault in the earlier LGM not saving the game icon. So the new version's behavior is technically correct, you really don't want to avoid that error message.

The IDE should ensure that the game icon is always there, which it now does, and it should error when it's not because the only way it can be deleted is by the user outside of the IDE. All that should be required is opening the projects one time and saving over the ones from the earlier LGM.

Just to be safe, I would make backups first. Not strictly necessary, but just safer as always. I recommend the same for GameMaker itself, Microsoft Word, any programs haha 👍

**Comment by Hughtech** [comment]
Ok then. Will get back when I've finished testing.
