### ISSUE TITLE
GMX loading failed to read a non-existent file.

### ISSUE THREAD

**Issue by SuperRiderTH** [IsmAvatar/LateralGM#362]
Upon loading a GMX, LGM gets cranky about an ico file not existing. 

```
LateralGM Version: 1.8.39

Operating System: Linux
Version: 4.13.0-37-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_151

Available processors (cores): 8
Free memory (bytes): 111787976
Maximum memory (bytes): 1828716544
Total memory available to JVM (bytes): 662700032

File system root: /
Total space (bytes): 59064549376
Free space (bytes): 44899086336
Usable space (bytes): 41868267520

Stack trace:
org.lateralgm.file.GmFormatException: failed to read: /home/sean/fusion-engine/Configs\Default\windows\runner_icon.ico
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:470)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:295)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:233)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/sean/fusion-engine/Configs\Default\windows\runner_icon.ico (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.lateralgm.file.StreamDecoder.<init>(StreamDecoder.java:45)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:75)
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:466)
	... 5 more
```

**Comment by RobertBColton** [comment]
Can you tell me if that file does in fact exist?

**Comment by RobertBColton** [comment]
Ah, I figured it out, while I was writing it with the `Util.getPOSIXPath` compatibility, I was not using the helper for reading the file back in, so Linux is looking for the wrong file. Easy fix.

**Comment by RobertBColton** [comment]
Give 1.8.40 a try:
https://github.com/IsmAvatar/LateralGM/releases

**Comment by SuperRiderTH** [comment]
The message no longer appears with 1.8.40. :ok_hand:

**Comment by RobertBColton** [comment]
Thanks, I think that should be good, but just to be safe I'd take another look at the project file. You might still have those sound files in the wrong place, but if they are in `sound/audio/` now you should be safe to delete the ones at the root of the project. Obviously, LGM, like GMS, never deletes files, it only writes or overwrites them.

**Comment by SuperRiderTH** [comment]
Alright. The audio files are in still in the audio folder, and saving doesn't spit them elsewhere anymore.
