### ISSUE TITLE
java error handling sprites in linux

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#375]
I've been getting this error when the number of sprites exceeds 50. this is the first time I've ever encountered this as I've never got it when working on a Linux 32bit platform.

-------------------------------------------------------------------------------------------------------------------------------
LateralGM Version: 1.8.40

Operating System: Linux
Version: 4.15.0-1-amd64
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_171

Available processors (cores): 2
Free memory (bytes): 19490504
Maximum memory (bytes): 796393472
Total memory available to JVM (bytes): 286785536

File system root: /
Total space (bytes): 155247083520
Free space (bytes): 108934393856
Usable space (bytes): 101024620544

Stack trace:
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
	at org.lateralgm.subframes.SpriteFrame.cleanup(SpriteFrame.java:1814)
	at org.lateralgm.subframes.SpriteFrame.dispose(SpriteFrame.java:1807)
	at javax.swing.JInternalFrame.doDefaultCloseAction(JInternalFrame.java:1635)
	at org.lateralgm.components.mdi.RevertableMDIFrame.close(RevertableMDIFrame.java:44)
	at org.lateralgm.subframes.ResourceFrame.doDefaultSaveAction(ResourceFrame.java:238)
	at org.lateralgm.subframes.ResourceFrame.actionPerformed(ResourceFrame.java:245)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

--------------------------------------------------------------------------------------------------------------------------

**Comment by RobertBColton** [comment]
This was a duplicate of #377 but #525 ultimately fixed it.
