### ISSUE TITLE
image edit crash in Java on Windows 7

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#377]
LateralGM Version: 1.8.40

Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_171

Available processors (cores): 2
Free memory (bytes): 13967904
Maximum memory (bytes): 259522560
Total memory available to JVM (bytes): 111898624

File system root: C:\
Total space (bytes): 159671906304
Free space (bytes): 128088686592
Usable space (bytes): 128088686592

File system root: D:\
Total space (bytes): 983960518656
Free space (bytes): 689568022528
Usable space (bytes): 689568022528

Stack trace:
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at org.lateralgm.subframes.SpriteFrame.cleanup(SpriteFrame.java:1814)
	at org.lateralgm.subframes.SpriteFrame.dispose(SpriteFrame.java:1807)
	at javax.swing.JInternalFrame.doDefaultCloseAction(Unknown Source)
	at org.lateralgm.components.mdi.RevertableMDIFrame.close(RevertableMDIFrame.java:44)
	at org.lateralgm.subframes.ResourceFrame.doDefaultSaveAction(ResourceFrame.java:238)
	at org.lateralgm.subframes.ResourceFrame.actionPerformed(ResourceFrame.java:245)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1536)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Hughtech** [comment]
When I edit any sprite this error comes up after I save in Mspaint.

**Comment by Hughtech** [comment]
Since that time LGM has been updated and this issue does not repeat itself.

**Comment by RobertBColton** [comment]
I ended up being able to reproduce this reliably in #525 and pushed 2eaf28b64f2e81b6abd16635573c090afa80b8a0 which fixes it. The 1.8.187 release is available now and contains the fix!
