### ISSUE TITLE
The EDIT action is not supported on the current platform!

### ISSUE THREAD

**Issue by mikeypro83** [IsmAvatar/LateralGM#378]
LateralGM Version: 1.8.40

Operating System: Linux
Version: 4.15.0-30-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_171

Available processors (cores): 2
Free memory (bytes): 136528184
Maximum memory (bytes): 893386752
Total memory available to JVM (bytes): 190840832

File system root: /
Total space (bytes): 74523631616
Free space (bytes): 8884301824
Usable space (bytes): 5075038208

Stack trace:
java.lang.UnsupportedOperationException: The EDIT action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:225)
	at java.awt.Desktop.edit(Desktop.java:300)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.start(SpriteFrame.java:1757)
	at org.lateralgm.subframes.SpriteFrame.editSubimage(SpriteFrame.java:1697)
	at org.lateralgm.subframes.SpriteFrame.editActionsPerformed(SpriteFrame.java:1279)
	at org.lateralgm.subframes.SpriteFrame.actionPerformed(SpriteFrame.java:1363)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mikeypro83** [comment]
I run Ubuntu 16.04 on an older dell laptop, bay trail cpu.

**Comment by JoshDreamland** [comment]
Oracle JVM or OpenJDK?

**Comment by RobertBColton** [comment]
Basically you just need to configure an image editor on your desktop so Java can find one, or specify a sprite editor command in Preferences. This is more of a user error than LGM, LGM just needs to be properly configured. See #386 which I plan to resolve by adding specialized error messages to direct the user to configure a sprite editor. This should stop people from posting this same error so many times.
