### ISSUE TITLE
LateralGM error to open preferences menu

### ISSUE THREAD

**Issue by hyperJJmaster** [IsmAvatar/LateralGM#383]
LateralGM Version: 1.8.41

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_191

Available processors (cores): 2
Free memory (bytes): 116151992
Maximum memory (bytes): 1363148800
Total memory available to JVM (bytes): 207618048

File system root: C:\
Total space (bytes): 104240246784
Free space (bytes): 46506680320
Usable space (bytes): 46506680320

File system root: D:\
Total space (bytes): 395248136192
Free space (bytes): 385163751424
Usable space (bytes): 385163751424

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 353370107904
Free space (bytes): 228026396672
Usable space (bytes): 228026396672

File system root: G:\
Total space (bytes): 331348963328
Free space (bytes): 52398186496
Usable space (bytes): 52398186496

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: J:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: K:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.lang.Error: Unresolved compilation problems: 
	The import org.lateralgm.joshedit cannot be resolved
	The import org.lateralgm.joshedit cannot be resolved
	The import org.lateralgm.joshedit cannot be resolved
	The import org.lateralgm.joshedit cannot be resolved
	The import org.lateralgm.joshedit cannot be resolved
	org.lateralgm.joshedit cannot be resolved to a type
	The method add(String, Component) in the type Container is not applicable for the arguments (HighlightPreferences, String)
	org.lateralgm.joshedit cannot be resolved to a type
	TokenMarker cannot be resolved to a type
	GMLTokenMarker cannot be resolved
	GLSLTokenMarker cannot be resolved
	GLESTokenMarker cannot be resolved
	HLSLTokenMarker cannot be resolved

	at org.lateralgm.subframes.PreferencesFrame.<init>(PreferencesFrame.java:83)
	at org.lateralgm.main.LGM.showPreferences(LGM.java:1488)
	at org.lateralgm.main.Listener.actionPerformed(Listener.java:509)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by RobertBColton** [comment]
I am really not sure why this error would have occurred unless you were building LateralGM yourself instead of using one of our prereleases. If that is the case, please understand that you should be recursively cloning the repo because JoshEdit is a submodule. So you would need `git clone --recursive` so the JoshEdit submodule is properly initialized.

**Comment by RobertBColton** [comment]
Alright, it's been a while and I've noticed some things so let me update this issue a little further.

I can see you have version 1.8.41 which we do not have a release for. So, that alone tells me you must have been building this yourself. You would need to ensure that you properly initialized the JoshEdit submodule or recursively cloned to fix this. Also, I personally use the Eclipse Jar description file to build the LGM jar for releases. I am not sure if you used the makefile, but that could explain why the JoshEdit errors were elided until runtime.

I don't see anything left for us to do on this issue or anything to fix, so I am going to close it. If you have more issues or would like to see the build changed in some way, please feel free to post a new issue.
