### ISSUE TITLE
GM81 Font AA Out of Bounds

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/LateralGM#418]
The GMK format has the AA levels shifted by one. That means that "off" is equal to 1 and "3" is equal to 4 when you are reading a GM81 GMK. This is not the case with the GMX format written by GMSv1.4, where the AA levels are 0-based. You can see this in the test GMK exported from GM8.1 I have provided with a font of each AA level.

Download GM81 Test GMK: [font_aa_test.zip](https://github.com/IsmAvatar/LateralGM/files/3145014/font_aa_test.zip)

If we open this GMK on the current master LGM, and then open "font_aa_3", we get the following exception. This is not a regression and occurs in lgm16b4.
```
AWT-EventQueue-0: 
java.lang.IllegalArgumentException: setSelectedIndex: 4 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:620)
	at org.lateralgm.ui.swing.propertylink.ComboBoxLink$IndexComboBoxConversion.select(ComboBoxLink.java:65)
	at org.lateralgm.ui.swing.propertylink.ComboBoxLink$IndexComboBoxConversion.select(ComboBoxLink.java:1)
	at org.lateralgm.ui.swing.propertylink.ComboBoxLink.setConvertedSelection(ComboBoxLink.java:128)
	at org.lateralgm.ui.swing.propertylink.ComboBoxLink.setComponent(ComboBoxLink.java:116)
	at org.lateralgm.util.PropertyLink.editComponent(PropertyLink.java:66)
	at org.lateralgm.util.PropertyLink.reset(PropertyLink.java:54)
	at org.lateralgm.ui.swing.propertylink.ComboBoxLink.<init>(ComboBoxLink.java:110)
	at org.lateralgm.ui.swing.propertylink.PropertyLinkFactory.make(PropertyLinkFactory.java:103)
	at org.lateralgm.subframes.FontFrame.<init>(FontFrame.java:149)
```

**Comment by RobertBColton** [comment]
Closing as resolved by #421.
