### ISSUE TITLE
Java error compiling on Linux

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#445]
LateralGM Version: 1.8.74

Operating System: Linux
Version: 4.19.56-1-MANJARO
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_222

Available processors (cores): 2
Free memory (bytes): 50891696
Maximum memory (bytes): 908066816
Total memory available to JVM (bytes): 232259584

File system root: /
Total space (bytes): 156451577856
Free space (bytes): 81259175936
Usable space (bytes): 73240489984

Stack trace:
java.lang.NullPointerException
	at java.lang.String.endsWith(String.java:1449)
	at org.lateralgm.components.impl.CustomFileFilter.accept(CustomFileFilter.java:53)
	at org.lateralgm.components.impl.CustomFileFilter.accept(CustomFileFilter.java:45)
	at javax.swing.JFileChooser.accept(JFileChooser.java:1650)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run0(BasicDirectoryModel.java:252)
	at javax.swing.plaf.basic.BasicDirectoryModel$LoadFilesThread.run(BasicDirectoryModel.java:228)

**Comment by Hughtech** [comment]
this happened after i tried to compile on my Linux 64bit computer. It runs within Enigma fine without any problems.

**Comment by RobertBColton** [comment]
This one seems to be my fault and stems from #364.

**Comment by RobertBColton** [comment]
I tested locally on my Oracle JDK on Windows, and sure enough, I got an exception passing null to endsWith called on a test string. I'll send a patch for the custom file filter.
```java
		String testHugar = "hugar";
		if (testHugar.endsWith(null)) testHugar = "hello";
```
