### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BeepBoop486** [IsmAvatar/LateralGM#463]
LateralGM Version: 1.8.89
Working Directory: /home/mya/enigma-dev/lateralgm.jar

Operating System: Linux
Version: 4.19.0-6-amd64
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Debian
Version: 11.0.5

Current Thread: main
Available processors (cores): 2
Free memory (bytes): 47958752
Maximum memory (bytes): 1000341504
Total memory available to JVM (bytes): 78643200

File system root: /
Total space (bytes): 212780994560
Free space (bytes): 199349620736
Usable space (bytes): 188469596160

Stack trace:
java.lang.NoClassDefFoundError: com/sun/jna/Pointer
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:705)
	at org.lateralgm.main.LGM.main(LGM.java:1167)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

**Comment by RobertBColton** [comment]
I suspect this is an issue with Java 11. Can you try the following to disable system JNA?
https://enigma-dev.org/docs/Wiki/Troubleshoot#Why_do_I_get_.22Can.27t_obtain_updateLastError.22_when_launching.3F

**Comment by RobertBColton** [comment]
Ah, Josh found it and I've sent https://github.com/enigma-dev/ExtraPackages/commit/80c286d9284372ed9798eafbcbba8802a09e2849 to the repo which fixes the 404 of JNA. Just repeat the `./install.py` or `./install.sh` step of the setup again. Sorry about that!
